package com.uptc.livestock.model.entity;

public enum Race {

	ABERDEEN_ANGUS, HOLSTEIN, GANADO_JERSEY, SHORTHORN, HEREFORD, SIMMENTAL, CHAROLESA, PARDO_SUIZO, GALLOWAY, LINOUSIN, CHIANINA, BELGIAN_BLUE, GELBVIEH, AYRSHIRE, DEVON_DEL_NORTE

}