package com.uptc.livestock.controller;

public enum Command {
	DISPOSE_LOGIN_JDIALOG, CREATE_ACCOUNT, FORGET_PASSWORD, LOGIN_ACCOUNT, SIGNIN_ACCOUNT,
	DISPOSE_SIGNIN_JDIALOG, SIGNIN_LOGIN, CONFIRM_FIELD, ABOUT, DISPOSE_NEWBOVINE_JDIALOG,
	ADD_BOVINE, NEW_COWDATA_RAD_BTN, NEW_BULLDATA_RAD_BTN, BTNCANCEL_NEWBOVINE_JDIALOG
}
