package com.uptc.livestock.controller;

public enum Command {
	DISPOSE_LOGIN_JDIALOG, CREATE_ACCOUNT, FORGET_PASSWORD, LOGIN_ACCOUNT, SIGNIN_ACCOUNT, DISPOSE_SIGNIN_JDIALOG, SIGNIN_LOGIN, CONFIRM_FIELD
}
